name: qr_mobile_vision_example
description: Demonstrates how to use the qr_mobile_vision plugin.

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  drawable_text:
    git:
      url: https://github.com/saedAlHanash/drawable_text
      ref: android

  image_multi_type:
    git:
      url: https://github.com/saedAlHanash/image_multi_type

  saed_http:
    git:
      url: https://github.com/saedAlHanash/saed_http

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.5
  get_it: ^7.6.7
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.2.2
  collection: ^1.18.0
  wakelock: ^0.6.2
  #  flutter_qr_bar_scanner: ^3.0.2
  #  qr_code_scanner: ^0.4.0 #not work
#  flutter_barcode_scanner: ^2.0.0 #not work
  #  flutter_qrcode_scanner: ^0.0.7
  audioplayers: ^5.0.0
  qr_mobile_vision: ^4.1.3
  flutter_screenutil: ^5.9.0
#  firebase_core: ^2.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/lotties/
    - assets/sounds/
    - assets/
